apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend # deployment name
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: cs3219-group8
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/peerprep-363807/frontend/frontend-image:latest
        imagePullPolicy: Always
        resources: {}
        # This app listens on port 3000 for web traffic.
        ports:
        - containerPort: 3000
        env:
        - name: URI_USER_SVC
          valueFrom:
            secretKeyRef:
              name: peerprep-secrets
              key: uri_user_svc