apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
spec:
  selector:
    matchLabels:
      app: question-service-app
  template:
    metadata:
      labels:
        app: question-service-app
        environment: prod
    spec:
      serviceAccountName: cs3219-group8
      containers:
      - name: question-service-app
        image: us-central1-docker.pkg.dev/peerprep-363807/question-service/question-service-image:latest
        # This app listens on port 8002 for web traffic.
        ports:
        - containerPort: 8002
        env:
        - name: NODE_ENV
          value: "prod"
        - name: USER
          valueFrom:
            secretKeyRef:
              name: peerprep-secrets
              key: username
        - name: HOST
          value: "127.0.0.1"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: peerprep-secrets
              key: password
        - name: PORT
          value: "5432"
        - name: PROD_DB
          valueFrom:
            secretKeyRef:
              name: peerprep-secrets
              key: database
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        command:
          - "/cloud_sql_proxy"
          - "-instances=peerprep-363807:us-central1:question-service=tcp:5432"
        securityContext:
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: question-service
spec:
  type: NodePort
  selector:
    app: question-service-app
  ports:
  - port: 8002 # port in service
    targetPort: 8002 # port in deployment