apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service-app
  ports:
  - port: 8000 # port in service
    targetPort: 8000 # port in deployment