apiVersion: v1
kind: Service
metadata:
  name: matching-service
spec:
  type: NodePort
  selector:
    app: matching-service-app
  ports:
  - port: 8001 # port in service
    targetPort: 8001 # port in deployment