apiVersion: v1
kind: Service
metadata:
  name: question-service
spec:
  type: NodePort
  selector:
    app: question-service-app
  ports:
  - port: 8002 # port in service
    targetPort: 8002 # port in deployment