name: Create GKE cluster and setup environment

on:
  workflow_dispatch:
    branches: [ "main", "prod", "automation" ]
  push:
    branches: [ "main", "prod", "automation" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER: peerprep-cluster2
  GKE_ZONE: us-central1

jobs:
  setup:
    name: Set up cluster
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Create cluster
        run: |-
          gcloud container clusters create-auto ${{ env.GKE_CLUSTER }} \
            --region ${{ env.GKE_ZONE }} \
            --project=${{ env.PROJECT_ID }}

      # Get the GKE credentials so we can deploy to the cluster
      - name: Set up GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      
