name: Scale down cron job

on: 
  workflow_dispatch:
    branches: [ "main", "prod" ]
  # schedule: 
  #   - cron: "0 18 * * *"  # every day at 6pm UTC (2am SGT)

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER: peerprep-cluster
  GKE_ZONE: us-central1

jobs:
  scale:
    name: Scale down to 0 replica
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          service_account_key: ${{ secrets.GKE_TERRAFORM_CREDS }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Set up GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_TERRAFORM_CREDS }}

      - name: Scale to 0 replicas
        run: |-
          kubectl delete deploy user-service matching-service question-service history-service communication-service collab-service frontend

